export enum CachePrefixKeys {
  CATEGORY,
  ACCOUNT,
  LIST_ACCOUNT_POSTS,
  LIST_NFT,
  LIST_POSTS,
  LIST_BLOGS,
  ACCOUNT_FOLLOWING,
  ACCOUNT_FOLLOWERS,
  ACCOUNT_SEARCH,
  ACCOUNT_BOOKMARKS,
  ACCOUNT_BALANCE,
}
