export enum CachePrefixKeys {
  MODEL_LIST,
  TEMPLATE_LIST,
  TEMPLATE_STATUS,
  TEMPLATE_EXTRACTOR_POINTCLOUD_NAME,
  TEMPLATE_EXTRACTOR_TEXT_NAME,
  TEMPLATE_ENDCODER_POINTCLOUD_NAME,
  TEMPLATE_ENDCODER_TEXT_NAME,
}
